"""Explicit clinical edits and newly authored choices; never learner-facing audit prose."""
import re
REFERENCES={
'Primary health care':{'title':'WHO: Declaration of Alma-Ata','url':'https://www.who.int/teams/social-determinants-of-health/declaration-of-alma-ata'},
'Infant feeding':{'title':'WHO: Infant and young child feeding','url':'https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding'},
'Family planning':{'title':'CDC: Contraception methods','url':'https://www.cdc.gov/contraception/about/index.html'},
'Prevention and screening':{'title':'WHO: Health concepts and prevention','url':'https://applications.emro.who.int/dsaf/dsa787.pdf'},
'Ethics and professionalism':{'title':'GMC: Professional standards','url':'https://www.gmc-uk.org/professional-standards'},
'Malignant hyperthermia':{'title':'MHAUS: Clinical recommendations','url':'https://www.mhaus.org/healthcare-professionals/mhaus-recommendations/'},
'Neuromuscular blockade':{'title':'DailyMed: Succinylcholine prescribing information','url':'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=04a4e6f5-6fa1-42e1-a3f9-21fca7786b15'}
}
INTRO_EXPLANATIONS={
1:'Clubbing causes usually painless enlargement of the distal digits and loss of the normal nail-bed angle.',
2:'Cyanosis can be harder to recognize in darker skin. Examine the tongue and oral mucosa for central cyanosis.',
3:'Pain is a symptom reported by the patient; tenderness is a sign elicited by examination.',
4:'Jaundice affects the sclera, whereas hypercarotenemia generally spares it.',
5:'Asthma does not usually cause clubbing. Clubbing warrants investigation for another underlying disease.',
6:'Small palpable lymph nodes can be normal. Size, site, consistency, mobility and associated symptoms determine concern.',
8:'A patch is a flat lesion larger than 1 cm; a macule is smaller than 1 cm.',
9:'The presenting-illness history explores the current complaint, severity, risk factors and differential diagnosis. A complete medication list is recorded in the drug history.',
10:'Educational attainment belongs to the social history. Past medical history includes illnesses, admissions and operations.',
13:'Myel/o refers to the spinal cord or bone marrow, depending on context; my/o refers to muscle.',
14:'The suffix -otomy means incision. -ectomy means removal and -ostomy means creation of an opening.',
15:'Erythr/o means red, leuk/o white, cyan/o blue and melan/o black.',
16:'Influenza is transmitted through respiratory particles. Droplet precautions are generally used in healthcare settings.',
17:'A therapeutic relationship requires trust, honesty, compassion and respect while maintaining professional boundaries.',
18:'Active listening includes appropriate distance, attentive body language and allowing the patient to speak without unnecessary interruption.',
19:'Good communication supports understanding, adherence, satisfaction and shared decisions; reducing consultation fees is not its clinical goal.',
23:'Prognosis describes the expected course and outcome of a disease; diagnosis identifies the disease.',
24:'Stenosis means abnormal narrowing of a passage or opening. Sclerosis means hardening.',
25:'The ilium is part of the pelvis; the ileum is part of the small intestine.',
26:'Suppuration is the formation or discharge of pus.',
27:'Patients should receive an honest explanation of errors affecting their care, along with appropriate remedial action.',
28:'Professionalism is taught through consistent role modelling, feedback and addressing unprofessional behaviour.',
29:'Inter- means between; intra- means within and peri- means around.',
30:'Herbal remedies and supplements belong in the medication history because they can have adverse effects and interactions.',
32:'Melena is black, tarry stool caused by digested blood. Fresh red rectal bleeding is hematochezia.',
33:'Consent is required before taking a history. A refusal should be respected and explored without coercion.',
35:'Paternalism gives the physician a dominant decision-making role and gives less weight to patient autonomy.',
38:'The plural of bronchus is bronchi.',
39:'Breaking bad news requires clear, sensitive communication, attention to emotions and a plan for support.',
40:'A communicable disease can be transmitted between people, directly or indirectly.',
41:'A focused history usually provides the starting point for the differential diagnosis, followed by examination and appropriate tests.',
42:'Standard precautions apply to all patients, including safe sharps handling and protection from blood and body-fluid exposure.',
43:'COPD alone does not usually cause clubbing. Clubbing in a patient with COPD should prompt assessment for another cause, such as lung cancer.',
45:'Consumerism emphasizes an informed patient taking an active role in choosing care rather than passively accepting physician authority.'}
def curate(q):
 token=q['token'];n=q['source']['originalQuestionNumber'];p=q['prefix'];s=q['stem'];e=q['explanation']
 if p in ('INTRO','INTROFINAL'):
  if p!='INTRO' or n not in INTRO_EXPLANATIONS or q['source']['page']>8:return 'Needs individual explanation and key review'
  q['explanation']=INTRO_EXPLANATIONS[n]
  if n==6:q['choices'][1]='Assess node size in the context of the anatomical site and clinical findings.'
  if n==16:q['stem']='Which of the following infections generally requires droplet precautions in a healthcare setting?'
  q['stem']=q['stem'].replace('All of the followings','All of the following').replace('All of the following is','All of the following are').replace('you much check','should you examine').replace('Set very close','Sit very close')
  q['choices']=[c.replace('scharmoth','Schamroth').replace('black race','people with darker skin') for c in q['choices']]
 if p=='NSQA':
  excluded={'NSQA-3-5','NSQA-5-9','NSQA-5-10','NSQA-16-4','NSQA-17-6','NSQA-22-10','NSQA-24-2','NSQA-25-4','NSQA-28-2','NSQA-30-8','NSQA-31-9'}
  if token in excluded:return 'Ambiguous anatomy, unsafe sequence or outdated treatment; needs rewrite'
  if token=='NSQA-2-1':
   q['correct']=2;q['stem']=s.replace('What is the best','He has no trauma, fever, cancer history or progressive neurological deficit. What is the best');q['explanation']='For uncomplicated low back pain without red flags, start conservative treatment and encourage normal activity. Routine imaging is not indicated.';q['references']=[{'title':'NICE NG59','url':'https://www.nice.org.uk/guidance/NG59/chapter/recommendations'}]
  if token=='NSQA-2-2':q['choices'][0]='Low back pain worsened by loading or movement and relieved by rest';q['explanation']='Mechanical back pain is typically related to loading or movement. Fever, constitutional symptoms or sphincter dysfunction require assessment for serious causes.'
  if token=='NSQA-3-4':q['stem']=s.replace('a disc herniation','a posterolateral disc herniation')
  if token=='NSQA-8-1':q['stem']='What is the most common malignant primary brain tumor in adults?';q['explanation']='Glioblastoma is the most common malignant primary brain tumor in adults. Meningioma is the most common primary brain tumor overall.'
  if token=='NSQA-9-4':q['explanation']='Pituitary microadenomas measure less than 10 mm; macroadenomas measure 10 mm or more. Suprasellar extension may compress the optic chiasm.'
  if token=='NSQA-10-9':q['explanation']='Meningiomas are typically dural-based, enhancing masses that may show a dural tail or calcification. These features are suggestive rather than pathognomonic.'
  if token=='NSQA-11-10':q['explanation']='Intracranial ependymomas are relatively common in children, whereas spinal ependymomas are more common in adults.'
  if token=='NSQA-11-11':q['explanation']='Meningiomas and nerve-sheath tumors are common intradural extramedullary tumors. Ependymomas typically arise within the spinal cord or from the filum terminale.'
  if token=='NSQA-20-5':q['explanation']='Concussion usually requires observation, symptom management and a gradual return to normal activity after a brief period of relative rest. Worsening symptoms require urgent reassessment.'
  if token=='NSQA-21-6':q['explanation']='Epidural hematomas are typically lentiform and limited by sutures. Subdural hematomas are crescentic and may cross sutures but are restricted by dural reflections such as the falx.'
  if token=='NSQA-22-9':q['stem']='What is the approximate normal intracranial pressure range in a supine adult?';q['choices'][q['correct']-1]='5–15 mmHg';q['explanation']='Normal intracranial pressure in a supine adult is approximately 5–15 mmHg. Interpretation depends on clinical context and measurement conditions.'
  if token=='NSQA-26-6':q['stem']='Which cervical instability is associated with Down syndrome and rheumatoid arthritis?';q['explanation']='Atlantoaxial instability can result from transverse ligament laxity or disease. Treatment depends on symptoms, instability and spinal cord compromise.'
  if token=='NSQA-31-10':q['stem']='What is the characteristic MRI appearance of a cerebral cavernous malformation?';q['explanation']='Mixed-age blood products produce a popcorn-like lesion with a hemosiderin rim on MRI. Cavernous malformations are usually angiographically occult.'
  if token=='NSQA-32-14':q['choices'][q['correct']-1]='Putamen (basal ganglia)';q['explanation']='Chronic hypertensive small-vessel disease commonly causes deep intracerebral hemorrhage, especially in the putamen. Other sites include the thalamus, pons and cerebellum.'
 if p=='OG':
  if token in ('OG-9-4','OG-11-9','OG-320-11','OG-356-47','OG-263-3'):return 'Underspecified, outdated or disputed clinical item'
  if re.search(r'failure rates? of contracept|failure rate.*contracept',s,re.I):return 'Typical versus perfect-use rates not specified'
  if 'methotrexate' in s.lower() and ('< 3000' in s or '< 3,000' in s or 'conditions' in s):return 'Eligibility cannot be determined by hCG alone'
  if token=='OG-10-7':q['explanation']='Persistent bleeding with a firm, contracted uterus after instrumental delivery suggests genital tract trauma. Inspect for cervical and vaginal lacerations while resuscitating and considering other causes.'
  if token=='OG-313-86':q['explanation']='The standard biophysical profile assesses fetal breathing, movement, tone, amniotic fluid volume and the non-stress test. Umbilical artery Doppler is a separate assessment.'
  if token=='OG-273-25':return 'Inherited thrombophilia versus antiphospholipid syndrome distinction unclear'
 if p=='PED':
  if re.search(r'Jordan|National Immunization Program|national.*schedule|first.line medications.*status epileptic',s,re.I):return 'Local schedule or treatment sequence needs current guideline verification'
  if token in ('PED-80-21','PED-129-56','PED-247-71','PED-286-11','PED-127-52'):return 'Choices do not establish one unambiguous best answer'
  if token=='PED-109-10':q['stem']=s.replace('A newborn aged 8 hours','A clinically stable newborn aged 8 hours');q['explanation']='In a stable newborn, swallowed maternal blood is a possible cause of early blood-stained vomiting. The Apt–Downey test can distinguish adult from fetal hemoglobin; clinical assessment should exclude significant neonatal bleeding.'
  if token=='PED-106-2':q['stem']='Which test directly demonstrates the characteristic small-intestinal mucosal changes of celiac disease?';q['explanation']='Duodenal biopsy demonstrates villous atrophy, crypt hyperplasia and increased intraepithelial lymphocytes. Selected children meeting strict serological criteria may be diagnosed without biopsy.'
  if token=='PED-8-2':q['stem']='Which congenital hypothalamic lesion is classically associated with central precocious puberty?';q['explanation']='Hypothalamic hamartomas can activate the hypothalamic–pituitary–gonadal axis and cause central precocious puberty. They may also cause gelastic seizures.'
  if token=='PED-14-16':q['choices'][0]='Mild pulmonary stenosis with intact ventricular septum';q['explanation']='In d-transposition, maintaining ductal patency with prostaglandin E1 can improve mixing between the parallel circulations. An inadequate atrial communication may require urgent balloon atrial septostomy.'
  if token=='PED-15-19':q['explanation']='Persistent bloody diarrhea with mucus and left-sided abdominal pain suggests ulcerative colitis. Infection must also be considered; Crohn disease can cause bloody diarrhea as well.'
  if token=='PED-12-11':q['explanation']='Acute rheumatic fever can cause severe migratory arthritis affecting large joints. It is generally non-deforming and responds rapidly to anti-inflammatory treatment.'
  if token=='PED-11-8':q['explanation']='Stool reducing substances suggest carbohydrate malabsorption. Steatorrhea and fat-soluble vitamin deficiency suggest fat malabsorption; a low fecal elastase supports pancreatic insufficiency.'
  if token=='PED-300-4':q['explanation']='The risk of common fetal autosomal trisomies increases with maternal age, largely because of meiotic nondisjunction.'
 if p=='RHEUM':
  if len(e)>1200 or not e:return 'Review table or adjacent-question contamination'
  if token=='RHEUM-8-18':q['explanation']='Common extra-articular features of spondyloarthritis include uveitis, psoriasis and inflammatory bowel disease. Glomerulonephritis is not a typical defining feature.'
  if token=='RHEUM-11-28':q['explanation']='Arthritis mutilans is a severe destructive form of psoriatic arthritis that can cause phalangeal osteolysis and telescoping digits.'
 if re.search(r'(?i)more than one option|debatably|question is flawed|ambiguous|not provided',q['explanation']):return 'Disputed source answer'
 if len(q['explanation'])<8:return 'Missing clinical explanation'
 if len(q['explanation'])>1400:return 'Adjacent source text contamination'
 return None

# Rows: subject, source hash, page, topic, stem, answer, distractors, explanation.
AUTHORED=[
(4,'d4123a760a93',2,'Prevention and screening','Vaccinating an uninfected person against a disease is an example of which level of prevention?','Primary prevention',['Secondary prevention','Tertiary prevention','Rehabilitation'],'Primary prevention acts before disease develops, for example through immunization or reducing exposure to risk factors.'),
(4,'d4123a760a93',2,'Prevention and screening','Screening an asymptomatic person to detect disease early is usually classified as which level of prevention?','Secondary prevention',['Primary prevention','Tertiary prevention','Palliative care'],'Secondary prevention aims to detect and treat disease early, before it progresses or causes substantial harm.'),
(4,'d4123a760a93',2,'Prevention and screening','Rehabilitation to reduce disability after an established stroke is an example of which level of prevention?','Tertiary prevention',['Primary prevention','Secondary prevention','Population screening'],'Tertiary prevention limits complications and disability from established disease and helps restore function.'),
(4,'c5570fa3b7dd',2,'Family planning','Which contraceptive method also reduces the risk of many sexually transmitted infections when used correctly?','Condoms',['Combined oral contraceptive pills','A contraceptive implant','An intrauterine device'],'Condoms provide a barrier that reduces pregnancy risk and transmission of many infections. Hormonal contraception and IUDs do not provide STI protection.'),
(4,'c5570fa3b7dd',2,'Family planning','Which option is a long-acting reversible contraceptive method?','A contraceptive implant',['Tubal sterilization','Vasectomy','Withdrawal'],'Implants and intrauterine devices provide long-acting contraception and can be removed when pregnancy is desired.'),
(4,'c5570fa3b7dd',2,'Family planning','Which nonhormonal device can be used for emergency contraception after unprotected intercourse, when clinically appropriate?','A copper intrauterine device',['A cervical cap inserted after intercourse','A vaginal diaphragm inserted after intercourse','A contraceptive implant'],'A copper IUD can be used within the recommended emergency-contraception window and then provides ongoing contraception.'),
(4,'c5570fa3b7dd',2,'Family planning','Which conditions are all required for the lactational amenorrhea method to be considered reliable?','Amenorrhea, fully or nearly fully breastfeeding, and less than 6 months postpartum',['Any breastfeeding and less than 12 months postpartum','Amenorrhea alone regardless of infant feeding','Breastfeeding once daily after menstrual cycles resume'],'Lactational amenorrhea requires all three criteria. Another method is needed when menstruation returns, breastfeeding decreases or the infant reaches 6 months.'),
(4,'4124403526bd',2,'Infant feeding','Which carbohydrate is the principal sugar in human breast milk?','Lactose',['Sucrose','Starch','Glycogen'],'Lactose is the major carbohydrate in human milk and contributes energy for infant growth.'),
(4,'4124403526bd',2,'Infant feeding','Which feature of human milk contributes to protection against gastrointestinal infections?','Secretory immunoglobulin A',['A lack of all immune proteins','A high concentration of unmodified cow-milk proteins','Absence of oligosaccharides'],'Human milk contains secretory IgA and other immune factors that help protect mucosal surfaces.'),
(4,'4124403526bd',2,'Infant feeding','WHO recommends exclusive breastfeeding for approximately how long after birth?','6 months',['2 weeks','2 months','12 months'],'Exclusive breastfeeding is recommended for the first 6 months, followed by appropriate complementary foods and continued breastfeeding.'),
]
AUTHORED.extend([
(5,'742a37a570bd',1,'Neurologic anatomy','Which glial cell forms myelin in the central nervous system?','Oligodendrocyte',['Schwann cell','Microglial cell','Ependymal cell'],'Oligodendrocytes form CNS myelin. Schwann cells form myelin in the peripheral nervous system.'),
(5,'742a37a570bd',2,'Neurologic anatomy','Which finding most strongly supports an established upper motor neuron lesion?','An extensor plantar response',['Marked fasciculations','Loss of tendon reflexes','Flaccid paralysis with focal wasting'],'An extensor plantar response indicates corticospinal tract dysfunction. Established upper motor neuron lesions commonly cause spasticity and hyperreflexia.'),
(5,'742a37a570bd',2,'Neurologic anatomy','Which tract lesion classically causes internuclear ophthalmoplegia?','Medial longitudinal fasciculus',['Optic tract','Spinothalamic tract','Fasciculus gracilis'],'A medial longitudinal fasciculus lesion impairs adduction of the ipsilateral eye during horizontal gaze, often with nystagmus of the abducting eye.'),
(5,'127004871935',1,'Multiple sclerosis','Multiple sclerosis primarily affects myelin in which location?','The central nervous system',['The neuromuscular junction','Peripheral sensory nerves only','Skeletal muscle fibres'],'Multiple sclerosis is an inflammatory demyelinating disease of the CNS, including the brain, optic nerves and spinal cord.'),
(5,'127004871935',3,'Multiple sclerosis','Which CSF finding supports a diagnosis of multiple sclerosis in the appropriate clinical setting?','CSF-restricted oligoclonal IgG bands',['Very low glucose with neutrophilic pleocytosis','Malignant cells','A positive bacterial culture'],'CSF-restricted oligoclonal bands indicate intrathecal immunoglobulin production. They support the diagnosis in context but are not specific to multiple sclerosis.'),
(5,'956aff4d4434',1,'Movement disorders','Which feature is central to the clinical syndrome of parkinsonism?','Bradykinesia',['Isolated sensory loss','Flaccid areflexia','Sudden visual loss'],'Parkinsonism requires bradykinesia with rigidity or rest tremor. Bradykinesia includes slowness and decrement of repetitive movement.'),
(8,'96174aabc074',14,'General anesthesia','Ketamine primarily produces anesthesia through antagonism of which receptor?','NMDA receptor',['Muscarinic acetylcholine receptor','Dopamine D2 receptor','Histamine H1 receptor'],'Ketamine produces dissociative anesthesia primarily through noncompetitive NMDA-receptor antagonism.'),
(8,'96174aabc074',27,'Neuromuscular blockade','Which drug is a depolarizing neuromuscular blocker?','Succinylcholine',['Rocuronium','Vecuronium','Cisatracurium'],'Succinylcholine activates nicotinic receptors and produces persistent depolarization. Rocuronium, vecuronium and cisatracurium are nondepolarizing blockers.'),
(8,'96174aabc074',11,'Malignant hyperthermia','Which drug is used to treat an acute malignant hyperthermia crisis?','Dantrolene',['Naloxone','Flumazenil','Protamine'],'Dantrolene reduces abnormal skeletal-muscle calcium release. Management also requires stopping triggering agents and immediate supportive treatment.'),
(8,'96174aabc074',11,'Malignant hyperthermia','Which combination can trigger malignant hyperthermia in a susceptible patient?','Volatile anesthetic agents and succinylcholine',['Propofol and fentanyl','Lidocaine and bupivacaine','Nitrous oxide and midazolam'],'Potent volatile anesthetics and succinylcholine are established malignant-hyperthermia triggers in susceptible individuals.'),
(4,'ffb355413118',1,'Primary health care','In which year was the Declaration of Alma-Ata adopted?','1978',['1948','1986','2000'],'The 1978 Declaration of Alma-Ata identified primary health care as essential to achieving health for all.'),
(4,'ffb355413118',1,'Primary health care','Which principle of primary health care means involving people in planning and delivering their care?','Community participation',['Exclusive specialist control','Hospital centralization','Commercial advertising'],'Primary health care involves individuals and communities in decisions about services and health priorities.'),
(4,'ffb355413118',1,'Primary health care','Which combination best reflects the scope of comprehensive primary health care?','Promotion, prevention, treatment and rehabilitation',['Emergency surgery only','Vaccination only','Treatment of established disease only'],'Comprehensive primary health care includes promotion, prevention, treatment and rehabilitation rather than a single type of service.'),
(4,'51f8e61bdaf0',2,'Communication skills','Which is an example of nonverbal communication?','Body posture and gestures',['The words chosen','Written instructions','The literal content of a question'],'Posture, gestures, facial expression and interpersonal distance convey nonverbal messages.'),
(4,'51f8e61bdaf0',2,'Communication skills','Which behaviour is a barrier to effective verbal communication?','Using unexplained medical jargon',['Using clear language','Organizing information','Checking understanding'],'Unexplained jargon can obscure meaning. Use plain language and check the patient’s understanding.'),
(4,'51f8e61bdaf0',2,'Communication skills','Which is NOT a supportive verbal listening technique?','Blaming the patient',['Paraphrasing','Summarizing','Reflecting feelings'],'Blame discourages disclosure and damages trust. Paraphrasing, summarizing and reflecting feelings support active listening.'),
(4,'4182abe4bcac',2,'Breaking bad news','In SPIKES, which step asks how much information the patient wants?','Invitation',['Perception','Knowledge','Strategy and summary'],'Invitation establishes the patient’s preference for the amount and detail of information.'),
(4,'4182abe4bcac',2,'Breaking bad news','In SPIKES, a warning shot before disclosing a serious diagnosis belongs to which step?','Knowledge',['Setting','Invitation','Strategy and summary'],'During Knowledge, a brief warning prepares the patient before clear, paced disclosure.'),
(4,'4182abe4bcac',2,'Breaking bad news','What does the P in SPIKES stand for?','Perception',['Prognosis','Prescription','Prevention'],'Perception explores what the patient already understands about the illness before new information is given.'),
(4,'4182abe4bcac',2,'Breaking bad news','Which action best illustrates the final S in SPIKES?','Agreeing on a plan and summarizing the discussion',['Withholding the diagnosis','Giving all information at once','Ignoring emotional responses'],'Strategy and summary consolidate understanding and agree on the next steps with the patient.'),
(4,'e912a84e8b3e',2,'Counseling','Which practice undermines effective counseling?','Rushing through the discussion',['Using a private setting','Maintaining confidentiality','Using clear language'],'Counseling requires sufficient time, privacy, a nonjudgmental approach and information the patient can understand.'),
(4,'e912a84e8b3e',2,'Counseling','Encouraging a sedentary patient to start regular exercise is an example of which behavioural goal?','Adding a beneficial behaviour',['Eliminating an addictive behaviour','Eliminating a nonaddictive behaviour','Changing the diagnosis'],'Starting exercise adds a health-promoting behaviour rather than removing an existing behaviour.'),
(4,'e912a84e8b3e',2,'Counseling','Which approach best supports achievable behaviour change?','Agreeing on a small number of realistic goals',['Changing every habit immediately','Giving orders without discussion','Avoiding follow-up'],'Patient-centred goals should be realistic, limited in number and supported by a practical plan and follow-up.'),
(4,'c27650c287bb',2,'Doctor–patient relationship','Which approach is inconsistent with patient-centred care?','An authoritarian approach that suppresses the patient’s views',['Open-ended questions','Exploring psychosocial concerns','Shared decision-making'],'Patient-centred care explores the patient’s concerns, values and circumstances and involves them in decisions.'),
(4,'029e4dc10fb8',2,'Difficult consultations','Which physician factor can contribute to a difficult consultation?','Fatigue',['A patient’s chronic pain','A patient’s unmet expectations','A patient’s functional impairment'],'Fatigue can reduce patience and communication quality. Difficult encounters can reflect clinician, patient and situational factors.'),
(4,'d4d4e70813bf',2,'Evidence-based medicine','Participants are randomly allocated to nicotine inhalers or nicotine patches. What is the study design?','Randomized controlled trial',['Case report','Cross-sectional study','Systematic review'],'Random allocation to intervention groups characterizes a randomized controlled trial.'),
(4,'d4d4e70813bf',2,'Evidence-based medicine','What does the C in PICO usually represent?','Comparison',['Clinical outcome','Consent','Case report'],'PICO organizes a clinical question into Population, Intervention, Comparison and Outcome.'),
(4,'7b97b3cdf4d8',2,'Diagnostic reasoning','Which usually provides the starting point for the differential diagnosis in a consultation?','A focused clinical history',['Routine imaging for everyone','Unselected laboratory panels','Ignoring the presenting complaint'],'History establishes the problem and likely diagnoses; examination and targeted investigations refine the assessment.'),
(4,'ed2df575d4b9',1,'Ethics and professionalism','Which ethical principle emphasizes promoting benefit for the patient?','Beneficence',['Autonomy','Justice','Confidentiality'],'Beneficence means acting to promote the patient’s welfare and weighing expected benefits against harms.'),
(4,'ed2df575d4b9',1,'Ethics and professionalism','What does accountability require of a physician?','Taking responsibility for professional actions',['Avoiding disclosure of errors','Delegating all decisions to patients','Prioritizing personal income'],'Accountability means accepting responsibility for actions, decisions and professional standards.'),
(4,'ed2df575d4b9',7,'Ethics and professionalism','Which ethical principle emphasizes avoiding harm?','Non-maleficence',['Autonomy','Justice','Beneficence'],'Non-maleficence requires avoiding unnecessary harm and considering treatment risks.'),
(4,'ed2df575d4b9',7,'Ethics and professionalism','A patient with decision-making capacity refuses a recommended treatment after understanding the risks. Which principle supports respecting that decision?','Autonomy',['Paternalism','Commercial interest','Professional convenience'],'Autonomy supports an informed, voluntary choice by a patient with decision-making capacity.'),
(4,'ed2df575d4b9',7,'Ethics and professionalism','Which principle supports fair allocation of limited healthcare resources?','Justice',['Personal preference','Financial profit','Paternalism'],'Justice requires fair allocation according to relevant clinical needs rather than irrelevant personal characteristics.'),
(4,'ed2df575d4b9',15,'Ethics and professionalism','What is an error of omission?','Failing to perform a necessary action',['Performing an unnecessary procedure','Giving the wrong medicine','Using the wrong dose'],'An omission is failure to take an indicated action; commission involves performing an incorrect action.'),
(4,'ed2df575d4b9',15,'Ethics and professionalism','What is positive defensive medicine?','Ordering unnecessary tests primarily to avoid litigation',['Avoiding all treatment','Practising evidence-based screening','Obtaining informed consent'],'Positive defensive medicine adds investigations or interventions primarily to reduce perceived legal risk rather than improve clinical care.'),
(3,'351e54a569c0',2,'Laboratory interpretation','Which laboratory pattern is typical of vitamin B12 deficiency?','Increased methylmalonic acid and homocysteine',['Normal methylmalonic acid and homocysteine','Increased homocysteine with normal methylmalonic acid','Decreased methylmalonic acid and homocysteine'],'Vitamin B12 is required for metabolism of both methylmalonic acid and homocysteine. Folate deficiency generally raises homocysteine without raising methylmalonic acid.'),
(3,'351e54a569c0',2,'Laboratory interpretation','A patient develops acute hemolysis after an oxidant antimalarial drug. Which underlying disorder should be considered?','G6PD deficiency',['Iron deficiency','Folate deficiency','Vitamin B12 deficiency'],'G6PD deficiency impairs red-cell protection against oxidative stress and may cause drug-triggered hemolysis.'),
(7,'1f32117273a7',1,'Metabolic bone disease','How do bisphosphonates reduce bone resorption?','Inhibiting osteoclast-mediated resorption',['Stimulating osteoclast proliferation','Inhibiting intestinal calcium absorption','Increasing parathyroid hormone release'],'Bisphosphonates concentrate in bone and inhibit osteoclast function, reducing bone resorption.'),
(7,'1f32117273a7',2,'Hand disorders','A patient cannot flex the thumb interphalangeal joint or index-finger distal interphalangeal joint. Which nerve is most likely affected?','Anterior interosseous nerve',['Posterior interosseous nerve','Ulnar nerve','Superficial radial nerve'],'The anterior interosseous nerve supplies flexor pollicis longus and the radial part of flexor digitorum profundus. Injury impairs the pinch or OK sign.'),
(7,'1f32117273a7',3,'Shoulder disorders','What is the most common direction of shoulder dislocation?','Anterior',['Posterior','Inferior','Superior'],'Most glenohumeral dislocations are anterior. Assess distal neurovascular function before and after reduction.'),
(7,'1f32117273a7',3,'Hand disorders','Which pulley is usually released surgically for persistent trigger finger?','A1 pulley',['A2 pulley','A3 pulley','A4 pulley'],'Trigger finger commonly involves narrowing at the A1 pulley. Release may be considered when conservative treatment fails.'),
(7,'1f32117273a7',4,'Shoulder disorders','Which rotator-cuff muscle primarily initiates shoulder abduction?','Supraspinatus',['Infraspinatus','Teres minor','Subscapularis'],'Supraspinatus initiates abduction; the deltoid provides most of the subsequent movement.'),
(7,'1f32117273a7',4,'Pediatric orthopedics','Most cases of achondroplasia arise through which mechanism?','A de novo FGFR3 mutation',['Autosomal recessive inheritance','A chromosome 21 trisomy','Mitochondrial inheritance'],'Achondroplasia is an autosomal dominant FGFR3 disorder, but most affected children have a new mutation.'),
(7,'1f32117273a7',5,'Foot and ankle','Which ligament is also known as the spring ligament?','Plantar calcaneonavicular ligament',['Anterior talofibular ligament','Deltoid ligament','Plantar calcaneocuboid ligament'],'The plantar calcaneonavicular ligament supports the talar head and helps maintain the medial longitudinal arch.'),
(7,'1f32117273a7',5,'Knee examination','McMurray’s test assesses which structure?','The knee menisci',['The anterior cruciate ligament','The posterior cruciate ligament','The quadriceps tendon'],'McMurray’s manoeuvre stresses the menisci during knee movement. Its findings must be interpreted with the history and other examination findings.'),
(7,'1f32117273a7',5,'Orthopedic emergencies','Which deformity may follow neglected forearm compartment syndrome?','Volkmann ischemic contracture',['Dupuytren contracture','Mallet finger','Boutonnière deformity'],'Ischemic muscle injury can lead to fibrosis and a fixed flexion contracture of the forearm and hand.'),
(7,'1f32117273a7',5,'Peripheral nerve injuries','On the MRC scale, movement through the full range with gravity eliminated corresponds to which grade?','Grade 2',['Grade 1','Grade 3','Grade 4'],'Grade 2 indicates active movement with gravity eliminated; grade 3 indicates movement against gravity.'),
(7,'1f32117273a7',6,'Orthopedic emergencies','What immediate step should accompany urgent assessment of suspected compartment syndrome beneath a tight cast?','Split or remove the constricting cast and padding',['Elevate the limb well above heart level','Wait for loss of the pulse','Discharge with oral analgesia'],'Remove external constriction and seek urgent surgical assessment. A preserved pulse does not exclude compartment syndrome, and confirmed disease requires urgent fasciotomy.'),
])

MATCHING=[{'subject_id':7,'hash':'3176be2de02e','page':4,'topic':'Spinal disorders','stem':'Match each clinical pattern to the most likely diagnosis. Each diagnosis may be used once, more than once, or not at all.','choices':['Cauda equina syndrome','Spinal epidural abscess','Metastatic spinal cord compression','Mechanical back pain','Vertebral compression fracture'],'matching':[{'stem':'Saddle anesthesia, bilateral sciatica and urinary dysfunction','correct':1},{'stem':'Back pain, fever and a neurological deficit in a person who injects drugs','correct':2},{'stem':'Known cancer with new back pain and progressive leg weakness','correct':3},{'stem':'Pain related to movement or loading that improves with rest, without red flags','correct':4},{'stem':'An older patient develops back pain after minor trauma; imaging shows a wedge-shaped vertebra','correct':5}],'explanation':'Sphincter dysfunction with saddle sensory loss suggests cauda equina syndrome. Fever with neurological deficits suggests infection. Cancer with progressive deficits raises concern for metastatic cord compression. Mechanical pain relates to loading, while a wedge deformity after minor trauma suggests a compression fracture.'}]
MATCHING.extend([
{'subject_id':7,'hash':'3176be2de02e','page':2,'number':8,'topic':'Knee injuries','stem':'Match each knee examination finding to the most likely injured structure or diagnosis. The same list is available for every branch.','choices':['Anterior cruciate ligament injury','Posterior cruciate ligament injury','Medial collateral ligament injury','Patellar dislocation','Meniscal injury'],'matching':[{'stem':'Excessive anterior translation of the tibia on Lachman testing','correct':1},{'stem':'Posterior sag of the tibia with the knee flexed to 90 degrees','correct':2},{'stem':'Medial joint pain and laxity with valgus stress','correct':3},{'stem':'Acute lateral displacement of the patella','correct':4},{'stem':'Joint-line pain with locking or clicking after a twisting injury','correct':5}],'explanation':'Lachman testing assesses the ACL, posterior sag suggests PCL injury and valgus stress assesses the MCL. Lateral patellar displacement indicates dislocation, while mechanical symptoms and joint-line pain suggest a meniscal injury.'},
{'subject_id':7,'hash':'3176be2de02e','page':3,'number':9,'topic':'Pediatric orthopedics','stem':'Match each child’s presentation to the most likely diagnosis. Each diagnosis may be used once, more than once, or not at all.','choices':['Transient synovitis','Slipped capital femoral epiphysis','Septic arthritis','Acute osteomyelitis','Legg–Calvé–Perthes disease'],'matching':[{'stem':'A well, afebrile 4-year-old develops a mild limp after a respiratory infection','correct':1},{'stem':'An adolescent with obesity has hip or referred knee pain, external rotation and restricted internal rotation','correct':2},{'stem':'A febrile child refuses to bear weight and has severe pain on passive hip movement','correct':3},{'stem':'A child has focal bone tenderness and fever','correct':4},{'stem':'A 6-year-old has a limp, limited hip abduction and femoral-head fragmentation and sclerosis on imaging','correct':5}],'explanation':'Transient synovitis commonly follows a viral illness in a well child. SCFE affects adolescents and limits internal rotation. Fever with severe pain on joint movement suggests septic arthritis; focal bone tenderness suggests osteomyelitis. Perthes disease causes avascular necrosis and fragmentation of the femoral head.'}
])
