import csv
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'reports/bau-specialties/curated.tsv'
with p.open(encoding='utf-8',newline='') as f:
 rows=list(csv.DictReader(f,delimiter='\t')); fields=list(rows[0])
extra='''46|61|5.1|5|Peripheral neuropathy|Progressive proximal and distal weakness, areflexia, and sensory loss have developed over six months. Which immune-mediated neuropathy is most consistent with this time course?|Chronic inflammatory demyelinating polyradiculoneuropathy|Acute inflammatory demyelinating polyradiculoneuropathy;Myasthenia gravis;Amyotrophic lateral sclerosis|CIDP generally progresses or relapses over more than eight weeks. Sensory involvement and areflexia support peripheral neuropathy rather than a pure motor or neuromuscular-junction disorder.
46|61|5.2|5|Peripheral neuropathy|Which CSF pattern can support CIDP in the appropriate clinical setting?|Elevated protein with a low or normal white-cell count|Marked neutrophilic pleocytosis with low glucose;Isolated oligoclonal bands as the defining finding;Persistently absent CSF protein|Albuminocytologic dissociation can occur in CIDP, but CSF findings are supportive and must be interpreted with clinical and electrodiagnostic criteria.
46|61|5.3|5|Peripheral neuropathy|On nerve histology, repeated demyelination and remyelination may produce which appearance?|Onion-bulb formations|Lewy bodies;Psammoma bodies;Neurofibrillary tangles|Concentric Schwann-cell processes around axons can form onion bulbs. This finding is not exclusive to CIDP and nerve biopsy is not routinely needed.
46|49|9.1|5|Multiple sclerosis|Internuclear ophthalmoplegia is caused by damage to which pathway?|Medial longitudinal fasciculus|Optic chiasm;Spinothalamic tract;Corticospinal tract in the lumbar cord|An MLF lesion disrupts conjugate horizontal gaze, impairing adduction of the ipsilateral eye and producing abducting nystagmus in the other eye.
46|46|6.1|5|Multiple sclerosis|Which painful disorders may occur in multiple sclerosis?|Optic neuritis and trigeminal neuralgia|Carpal tunnel syndrome and gout as defining criteria;Acute angle-closure glaucoma and plantar fasciitis;Temporal arteritis and appendicitis|Optic neuritis often causes pain with eye movement. Trigeminal neuralgia can result from demyelination involving trigeminal pathways.
46|88|dystonia-treatment|5|Movement disorders|Which local treatment is commonly used for cervical dystonia?|Botulinum toxin injection into selected affected muscles|IV thrombolysis;High-dose levodopa in every case;Long-term phenytoin as first-line treatment|Targeted botulinum toxin reduces excessive contraction in affected muscles. Selection, dose, and injection technique require clinical expertise.
46|88|dystonia-mechanism|5|Movement disorders|How does botulinum toxin reduce skeletal muscle contraction?|Inhibits presynaptic acetylcholine release at the neuromuscular junction|Blocks central dopamine receptors;Stimulates postsynaptic nicotinic receptors;Inhibits acetylcholinesterase|Botulinum toxin disrupts vesicle release machinery, reducing acetylcholine release and neuromuscular transmission.
46|86|chorea-genetics|5|Movement disorders|Huntington disease results from a CAG expansion in HTT on which chromosome?|Chromosome 4|Chromosome 7;Chromosome 17;Chromosome 21|HTT is located on chromosome 4. Huntington disease follows autosomal dominant inheritance.
46|312|dementia-reversible|5|Dementia|Which is a potentially treatable contributor to cognitive impairment that should be considered in a dementia evaluation?|Vitamin B12 deficiency|Huntington disease;Advanced Alzheimer disease;Dementia with Lewy bodies|B12 deficiency, thyroid dysfunction, medications, and other contributors should be assessed where appropriate. Correction does not guarantee reversal of all cognitive impairment.
46|223|best-motor|6|Head and spinal injury|A patient has left hemiplegia but obeys commands with the right hand. What is the best GCS motor response score?|6|3;4;5|GCS motor scoring records the best response. Obeying commands scores 6 even when another limb is weak.
46|195|spinal-injury-steroids|6|Head and spinal injury|Under NICE guidance, what is the role of high-dose methylprednisolone for neuroprotection after acute traumatic spinal cord injury?|It should not be administered for this purpose|It is mandatory in every patient within eight hours;It replaces airway and circulatory stabilization;It is first-line treatment for spinal hemorrhage|NICE advises against methylprednisolone for neuroprotection in acute traumatic spinal cord injury. The older source's blanket eight-hour steroid recommendation was corrected.
46|196|dermatome|6|Spinal disorders|The umbilicus is a landmark for which dermatome?|T10|T4;T6;L1|T10 is the conventional umbilical dermatome landmark; the nipple line is approximately T4. A sensory level requires a full neurological examination.
46|184|sacral-sparing|6|Head and spinal injury|What finding is essential to assess before classifying a spinal cord injury as AIS A, complete?|Absence of sensory and motor function in sacral segments S4–S5|A sensory level at T4 alone;Inability to walk without assessing sacral function;A single abnormal knee reflex|Complete injury requires absence of sacral sensory and motor sparing. Paraplegia or a sensory level alone does not establish AIS A.
72|33|compression-rate|8|Resuscitation|What chest-compression rate is recommended during adult CPR?|100–120 compressions/minute|60–80 compressions/minute;80–90 compressions/minute;140–160 compressions/minute|High-quality adult CPR uses 100–120 compressions per minute with full recoil and minimal interruption. The source's unbounded at-least-100 wording was clarified.
72|7|compression-ratio|8|Resuscitation|For adult CPR without an advanced airway, what compression-to-ventilation ratio is used?|30:2|15:2;5:1;3:1|Use 30 compressions to two breaths before an advanced airway is placed. With an advanced airway, compressions continue while ventilations are delivered separately.
72|8|vf-next|8|Resuscitation|During adult cardiac arrest, the monitor shows ventricular fibrillation. Which intervention is indicated promptly while minimizing interruptions to CPR?|Defibrillation|Synchronized cardioversion;Atropine before any shock;Observation for spontaneous conversion|VF is a shockable arrest rhythm. Deliver an unsynchronized shock promptly and resume CPR immediately afterward.
72|10|asystole|8|Resuscitation|Which medication is indicated as soon as feasible during adult asystolic cardiac arrest in addition to high-quality CPR?|Epinephrine|Adenosine;Atropine as routine first-line therapy;Verapamil|Asystole is nonshockable. Continue CPR, give epinephrine, and evaluate reversible causes; routine defibrillation is not indicated.
72|19|post-shock|8|Resuscitation|Immediately after delivering a shock for VF during cardiac arrest, what should the team do?|Resume CPR immediately|Pause for a prolonged pulse check;Wait for spontaneous breathing;Give synchronized cardioversion immediately|Resume chest compressions immediately after a shock, minimizing hands-off time, and continue the algorithm.
48|2|preoxygenation|8|Airway management|What is the main benefit of effective preoxygenation before induction?|Replaces alveolar nitrogen with oxygen and increases the oxygen reserve during apnea|Creates a permanent increase in functional residual capacity;Eliminates every aspiration risk;Prevents all difficult intubations|Preoxygenation denitrogenates the lungs and increases oxygen stores. The source's claim that its main action is increasing FRC was corrected.
48|1|transfusion-calcium|8|Blood products|Rapid transfusion of citrate-containing blood products can cause which electrolyte disturbance?|Hypocalcemia|Hypercalcemia;Hypermagnesemia;Isolated hypernatremia as the defining effect|Citrate binds ionized calcium. Monitor ionized calcium during substantial transfusion and correct abnormalities when indicated.
51|3|pseudocholinesterase|8|Perioperative pharmacology|Which pair may produce prolonged paralysis in a patient with substantial plasma cholinesterase deficiency?|Succinylcholine and mivacurium|Rocuronium and vecuronium;Atracurium and cisatracurium;Propofol and etomidate|Succinylcholine and mivacurium depend on plasma cholinesterase metabolism. Deficiency can markedly prolong their effects.
48|2|acquired-cholinesterase|8|Perioperative pharmacology|Which pair can contribute to acquired low plasma cholinesterase activity?|Severe liver disease and malnutrition|Essential tremor and uncomplicated myopia;Isolated ankle sprain and osteoid osteoma;Well-controlled hypertension and uncomplicated migraine|Plasma cholinesterase is synthesized in the liver; severe liver disease and malnutrition may reduce activity. Clinical impact depends on severity and other factors.
60|4|kanavel|7|Hand disorders|A swollen finger is held in slight flexion, with tenderness along the flexor sheath and pain on passive extension. Which diagnosis is most concerning?|Pyogenic flexor tenosynovitis|Mallet finger;Trigger finger without infection;De Quervain tenosynovitis|These are Kanavel signs of flexor-sheath infection. Urgent hand-surgery assessment and antibiotics are required; operative drainage may be needed.
60|11|knee-dislocation|7|Orthopedic emergencies|After a traumatic tibiofemoral knee dislocation, which arterial injury requires particular attention even after reduction?|Popliteal artery injury|Radial artery injury;Posterior circumflex humeral artery injury;Dorsal carpal artery injury|Knee dislocation can damage the popliteal artery. A palpable pulse does not exclude injury; perform appropriate vascular assessment and monitoring.
60|43|plateau-plafond|7|Fractures|Which anatomical region is the tibial plateau?|Proximal tibial articular surface at the knee|Distal tibial articular surface at the ankle;Midshaft tibial cortex;Head of the fibula|The plateau is proximal at the knee. The tibial plafond is the distal tibial articular surface at the ankle.
60|76|trigger-finger|7|Hand disorders|Trigger finger usually involves impaired flexor tendon gliding at which pulley?|A1 pulley|A2 pulley;A3 pulley;A4 pulley|Stenosing flexor tenosynovitis commonly affects the A1 pulley. Treatment depends on severity and includes injections or release when indicated.
60|78|vertical-talus|7|Pediatric orthopedics|A rigid congenital rocker-bottom foot is classically associated with which deformity?|Congenital vertical talus|Flexible flatfoot;Idiopathic clubfoot;Metatarsus adductus|Congenital vertical talus produces a rigid rocker-bottom deformity. It requires specialist assessment and differs from a flexible flatfoot.
60|95|spondylolysis|7|Spinal disorders|Spondylolysis refers to a defect in which part of a vertebra?|Pars interarticularis|Spinous process alone;Intervertebral disc nucleus;Vertebral endplate alone|A pars defect is spondylolysis. Forward displacement of a vertebra is spondylolisthesis, which can occur with bilateral pars defects.
60|100|pes-cavus|7|Foot and ankle|Pes cavus describes which foot shape?|An abnormally high medial longitudinal arch|Loss of the medial longitudinal arch;A lateral deviation of the great toe only;A normal flexible arch|Pes cavus is a high-arched foot. The source's description as loss of the arch was incorrect; loss of the arch describes pes planus.
60|84|bankart|7|Shoulder disorders|A Bankart lesion after anterior shoulder dislocation involves which structure?|Anteroinferior glenoid labrum|Posterolateral humeral head alone;Supraspinatus tendon insertion alone;Acromioclavicular capsule alone|A Bankart lesion is an anteroinferior labral injury. A Hill-Sachs lesion is an impaction defect of the posterolateral humeral head.
60|94|scheuermann|7|Spinal disorders|Adolescent structural kyphosis with vertebral wedging and Schmorl nodes suggests which condition?|Scheuermann disease|Ankylosing spondylitis;Lumbar spondylolysis;Idiopathic scoliosis without kyphosis|Scheuermann disease causes structural kyphosis, often with consecutive anterior vertebral wedging and endplate changes including Schmorl nodes.'''
seen={(r['source'],r['page'],r['original']) for r in rows}
for line in extra.splitlines():
 values=line.split('|');assert len(values)==len(fields),(line,len(values))
 row=dict(zip(fields,values))
 if tuple(row[k] for k in ['source','page','original']) not in seen:rows.append(row)
with p.open('w',encoding='utf-8',newline='') as f:
 writer=csv.DictWriter(f,fieldnames=fields,delimiter='\t');writer.writeheader();writer.writerows(rows)
