(function(){
'use strict';
const paths={fullscreenExit:'M3 8h5V3m8 0v5h5M3 16h5v5m8 0v-5h5',eye:'M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12 M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',eyeOff:'m3 3 18 18M10.5 5.1 12 5c6.5 0 10 7 10 7a17 17 0 0 1-3.2 3.9M6.3 6.3A19 19 0 0 0 2 12s3.5 7 10 7a12 12 0 0 0 5.7-1.7M10 10a3 3 0 0 0 4 4',previous:'m15 5-7 7 7 7',next:'m9 5 7 7-7 7',report:'m5 12 4 4L19 6',labs:'M9 3h6M10 3v7l-5 8a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-8V3M8 16h8',calculator:'M6 3h12v18H6zM9 6h6M9 11h1m4 0h1m-6 4h1m4 0h1m-6 3h1m4 0h1',help:'M9 9a3 3 0 1 1 5 2c-2 1-2 2-2 3M12 18h.01',pause:'M8 5v14M16 5v14',settings:'M12 3v3m0 12v3M3 12h3m12 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',notes:'M5 17 16 6l3 3L8 20H5v-3M14 8l3 3',library:'M3 7v14h14M7 3h14v14H7zM10.5 7h7M10.5 10h7M10.5 13H15',end:'m7 7 10 10M7 17 17 7',fullscreen:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5',mark:'M5 21V3h13l-3 5 3 5H5'};
const gear=`<svg viewBox="0 0 16 16" fill="currentColor" aria-hidden="true"><path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"/></svg>`;
const svg=name=>name==='settings'?gear:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]}"/></svg>`;
const flag=`<svg viewBox="0 0 16 16" fill="red" stroke="black" stroke-width=".5" aria-hidden="true"><path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12 12 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A20 20 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a20 20 0 0 0 1.349-.476l.019-.007.004-.002h.001"/></svg>`;
const button=(action,label,shape=action)=>`<button type="button" data-nbme="${action}">${svg(shape)}<span>${label}</span></button>`;
window.QnexNbmeLayout={render(engine,q,layout){
 const root=engine.el.container,secondary=layout==='nbme-secondary';root.querySelectorAll('.nbme-header,.nbme-footer').forEach(n=>n.remove());
 const header=document.createElement('header');header.className='nbme-header';
 header.innerHTML=`<div class="nbme-position">${secondary?'Item:':'Exam Section 1 <i class="nbme-divider"></i> Item:'} ${engine.state.currentIndex+1} of ${engine.state.questions.length}${secondary?'<small>'+ (q._tutorMode===false?'Exam Mode':'Tutor Mode')+'</small>':''}</div>${secondary?`<div class="nbme-nav">${button('previous','Previous')}${button('next','Next')}</div><div class="nbme-tools">${button('labs','Lab Values')}${button('notes','Notes')}${button('calculator','Calculator')}${button('fullscreen','Fullscreen')}${button('settings','Settings')}</div>`:'<div class="nbme-title">NBME Self-Assessments</div>'}`;
 const footer=document.createElement('footer');footer.className='nbme-footer';
 footer.innerHTML=secondary?`<div class="nbme-footer-left"></div><div class="nbme-footer-right">${button('library','Medical Library')}${button('notebook','My Notebook','notes')}${button('suspend','Suspend','pause')}${button('end','End Block')}</div>`:`<div class="nbme-footer-left">${button('previous','Previous')}${button('next','Next')}</div><div class="nbme-footer-right">${button('labs','Lab Values')}${button('calculator','Calculator')}${button('suspend','Suspend','pause')}${button('end','End Block')}</div>`;
 const submitted=!!engine.state.answers.get(q.id)?.submitted,locked=q.revealed||q._caseAdvanced||q._timedOut;
 if(secondary){const submit=document.createElement('button');submit.type='button';submit.className='nbme-inline-submit';submit.textContent=submitted?'Submitted':locked?'Answer shown':'Submit';submit.disabled=submitted||!!locked;submit.onclick=()=>engine.handleSubmit();engine.el.main.querySelector('.dungeon-options-list')?.after(submit);}else if(!submitted&&!locked)footer.querySelector('.nbme-footer-left').insertAdjacentHTML('beforeend',button('submit','Submit','report'));
 if(q._tutorMode!==false && engine.caseFeedbackAllowed(q))footer.querySelector('.nbme-footer-left').insertAdjacentHTML('beforeend',button('answer',q.revealed?'Hide Answer':'Show Answer',q.revealed?'eyeOff':'eye'));
 const timed=q._timerMode==='down';
 footer.querySelector('.nbme-footer-left').insertAdjacentHTML('afterbegin','<div class="nbme-session-status"><strong data-nbme-clock>00:00:00</strong><span>'+(timed?'Remaining':'Elapsed')+' · '+(q._tutorMode===false?'Exam':'Tutor')+' · '+(timed?'Timed':'Untimed')+'</span></div>');
 if(secondary)header.querySelectorAll('[data-nbme="previous"],[data-nbme="next"]').forEach(control=>{control.querySelector('svg').outerHTML='<svg class="nbme-round-nav" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="11" fill="var(--theme-topbar-bg, white)" stroke="var(--theme-topbar-text, black)" stroke-width="1.5"/><path d="M12 7l5 5-5 5m5-5H7" stroke="var(--theme-topbar-text, black)" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" fill="none"'+(control.dataset.nbme==='previous'?' transform="rotate(180 12 12)"':'')+'/></svg>';});
 root.append(header,footer);
 const syncFullscreen=()=>{const active=!!(document.fullscreenElement||document.webkitFullscreenElement);const control=root.querySelector('[data-nbme=fullscreen]');if(control){control.innerHTML=svg(active?'fullscreenExit':'fullscreen')+'<span>'+(active?'Exit fullscreen':'Fullscreen')+'</span>';control.setAttribute('aria-pressed',String(active));}};
 if(engine._nbmeFullscreenSync){document.removeEventListener('fullscreenchange',engine._nbmeFullscreenSync);document.removeEventListener('webkitfullscreenchange',engine._nbmeFullscreenSync);}engine._nbmeFullscreenSync=syncFullscreen;document.addEventListener('fullscreenchange',syncFullscreen);document.addEventListener('webkitfullscreenchange',syncFullscreen);syncFullscreen();engine.updateTimerDisplay(engine.lastTimerMs||0);
 if(!secondary){const settings=document.createElement('button');settings.type='button';settings.className='nbme-settings-open';settings.setAttribute('aria-label','Exam settings');settings.innerHTML=svg('settings')+'<span>Settings</span>';settings.onclick=()=>window.QnexNbmeLayout.settings(engine,settings);header.append(settings);}
 root.style.setProperty('--nbme-text-size',({small:16,medium:18,large:21}[localStorage.getItem('dungeonFontSize')]||18)+'px');root.dataset.nbmeAppearance=localStorage.getItem('nbmeAppearance')||'light';root.dataset.nbmeTextAlign=localStorage.getItem('nbmeTextAlign')||'left';

 {
 if(secondary)engine.el.sidebar.classList.remove('collapsed');
 const toggle=document.createElement('button');toggle.type='button';toggle.className='nbme-sidebar-toggle';toggle.setAttribute('aria-label','Toggle question navigation');toggle.innerHTML=engine.el.container.querySelector('#dungeonSidebarToggle')?.innerHTML||'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6h18M3 12h18M3 18h18"/></svg>';
 toggle.insertAdjacentHTML('beforeend','<span>Items</span>');toggle.setAttribute('aria-expanded',String(secondary?!root.classList.contains('nbme-sidebar-hidden'):root.classList.contains('nbme-sidebar-open')));toggle.setAttribute('aria-controls','dungeonSidebar');
 toggle.onclick=()=>{engine.el.sidebar.classList.remove('collapsed');if(window.QnexResponsive?.isDrawer())window.QnexResponsive.toggleDrawer('exam',toggle);else{if(secondary)root.classList.toggle('nbme-sidebar-hidden');else root.classList.toggle('nbme-sidebar-open');engine.el.sidebar.classList.remove('collapsed');engine.el.sidebar.style.removeProperty('display');toggle.setAttribute('aria-expanded',String(secondary?!root.classList.contains('nbme-sidebar-hidden'):root.classList.contains('nbme-sidebar-open')));}};if(secondary){const group=document.createElement('div');group.className='nbme-header-item-group';const position=header.querySelector('.nbme-position');position.before(group);group.append(toggle,position);}else header.querySelector('.nbme-position').prepend(toggle);
 }
 {const sidebar=engine.el.sidebar;sidebar.querySelector('.nbme-sidebar-heading')?.remove();const heading=document.createElement('div');heading.className='nbme-sidebar-heading';heading.innerHTML='Question<br>Status';sidebar.prepend(heading);
 sidebar.querySelectorAll('.dungeon-q-box').forEach((row,i)=>{
 const item=engine.state.questions[i],answer=engine.state.answers.get(item.id);const visible=answer?.submitted&&(engine.state.isBlockRevealed||(item._tutorMode!==false&&engine.caseFeedbackAllowed(item)));
 const path=visible?(answer.isCorrect?'m4 12 5 5L20 6':'m6 6 12 12M18 6 6 18'):'';
 row.innerHTML='<span class="nbme-row-status" style="color:'+(visible?(answer.isCorrect?'#17812b':'#d33'):'#17202c')+'"><svg viewBox="0 0 24 24" aria-hidden="true">'+(visible?'<path d="'+path+'" fill="none" stroke="currentColor" stroke-width="2.5"/>':'<circle cx="12" cy="12" r="4" fill="currentColor"/>')+'</svg></span><span class="nbme-row-number">'+(i+1)+'</span>'+((item.starred||item.isStarred)?'<span class="nbme-row-flag">'+flag+'</span>':'');
 });
 }
 const currentAnswer=engine.state.answers.get(q.id);
 const stem=engine.el.main.querySelector('.dungeon-context-box');
 if(stem){
 const wrap=document.createElement('div');wrap.className='nbme-question-line';stem.before(wrap);wrap.append(stem);
 const status=document.createElement('span');status.className='nbme-question-result';const feedback=currentAnswer?.submitted&&(engine.state.isBlockRevealed||(q._tutorMode!==false&&engine.caseFeedbackAllowed(q)));
 status.innerHTML=(feedback?'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" role="img" aria-label="'+(currentAnswer.isCorrect?'Correct':'Incorrect')+'" style="color:'+(currentAnswer.isCorrect?'#17812b':'#d33')+'"><path d="'+(currentAnswer.isCorrect?'m4 12 5 5L20 6':'m6 6 12 12M18 6 6 18')+'"/></svg>':'')+'<span>'+(engine.state.currentIndex+1)+'.</span>';wrap.prepend(status);
 if(secondary){engine._nbmeIndentObserver?.disconnect();const syncIndent=()=>{if(status.isConnected)root.style.setProperty('--nbme-stem-indent',(status.getBoundingClientRect().width+8)+'px');};syncIndent();if(window.ResizeObserver){engine._nbmeIndentObserver=new ResizeObserver(syncIndent);engine._nbmeIndentObserver.observe(status);}}

 const highlight=event=>{const mode=engine.state.highlightMode,color=engine.state.activeHighlightColor;engine.state.highlightMode=true;engine.state.activeHighlightColor='yellow';try{engine.handleHighlight(event,'main');}finally{engine.state.highlightMode=mode;engine.state.activeHighlightColor=color;}};
 stem.onmouseup=highlight;stem.ontouchend=()=>setTimeout(()=>highlight({currentTarget:stem,target:window.getSelection()?.anchorNode?.parentElement||stem}),80);
 stem.onkeyup=event=>{if(event.shiftKey)highlight(event);};
 }

 engine.el.main.querySelectorAll('.dungeon-radio-option').forEach((row,i)=>{row.dataset.optionId=String(q.options[i]?.id);if(secondary){const strike=document.createElement('button');strike.type='button';strike.className='nbme-option-strike';strike.setAttribute('aria-label','Cross out option '+String.fromCharCode(65+i));strike.setAttribute('aria-pressed',String((q.crossedOutOptionIds||[]).includes(String(q.options[i]?.id))));strike.innerHTML='<span>ab</span>';strike.onclick=event=>{event.stopPropagation();engine.handleStrikeOption(event,strike);};row.append(strike);}});
 engine.el.main.querySelectorAll('.dungeon-option-letter').forEach((label,i)=>label.textContent=String.fromCharCode(65+i)+')');
 const explanation=engine.el.main.querySelector('.dungeon-explanation')||root.querySelector('#dungeonExplanationContent .dungeon-explanation');
 if(explanation){const feedback=explanation.querySelector('.dungeon-feedback');if(feedback){const correct=(q.options||[]).map((o,i)=>o.isCorrect?String.fromCharCode(65+i):'').filter(Boolean).join(', ');feedback.className='nbme-correct-answer';feedback.textContent='Correct Answer: '+(correct||'—')+'.';if(/correct\s+answer\s*:/i.test(explanation.querySelector(':scope > div:last-of-type')?.textContent||''))feedback.remove();}if(!q.explanation?.trim()&&!q.richExplanation?.trim()&&!(q.explanationMedia||[]).length){const notice=document.createElement('p');notice.className='nbme-source-notice';notice.textContent='No explanation is included in this source question.';explanation.append(notice);}}
 if(explanation){
 const imageKey=img=>{const src=img.getAttribute('src')||img.getAttribute('data-src')||'';if(!src)return '';try{const url=new URL(src,document.baseURI);url.hash='';return url.href;}catch{return src;}};
 const questionImages=new Set([...engine.el.main.querySelectorAll('.dungeon-context-box img')].map(imageKey).filter(Boolean));
 explanation.querySelectorAll('img').forEach(img=>{if(questionImages.has(imageKey(img))){const picture=img.closest('picture');if(picture)picture.remove();else img.remove();}});
 explanation.querySelectorAll('figure').forEach(figure=>{if(!figure.querySelector('img,video,svg'))figure.remove();});
 explanation.querySelectorAll('*').forEach(el=>{if(!el.closest('table,pre,code')){for(const prop of ['margin','margin-top','margin-bottom','padding-top','padding-bottom','min-height','height','white-space'])el.style.removeProperty(prop);}});
 explanation.querySelectorAll('p,div,span').forEach(el=>{if(!el.textContent.replace(/\u00a0/g,' ').trim()&&!el.querySelector('img,svg,video,table,hr'))el.remove();});
 explanation.querySelectorAll('p,div').forEach(el=>{if(/^Educational Objective\s*:/i.test(el.textContent.trim())&&!el.querySelector('p,div'))el.classList.add('nbme-objective');});
 explanation.querySelectorAll('br').forEach(br=>{let next=br.nextSibling;while(next&&next.nodeType===3&&!next.textContent.trim())next=next.nextSibling;let prev=br.previousSibling;while(prev&&prev.nodeType===3&&!prev.textContent.trim())prev=prev.previousSibling;const block=node=>node?.nodeType===1&&/^(P|DIV|SECTION|ARTICLE|H[1-6]|UL|OL|TABLE)$/.test(node.nodeName);if(!next||!prev||next.nodeName==='BR'||block(next)||block(prev))br.remove();});
 }
 const mark=document.createElement('button');mark.type='button';mark.className='nbme-mark';mark.innerHTML='<input type="checkbox" tabindex="-1" aria-hidden="true" '+(q.starred?'checked':'')+'>'+flag+'<span>Mark Question</span>';mark.setAttribute('aria-label',q.starred?'Unmark question':'Mark question');mark.setAttribute('aria-pressed',String(!!q.starred));mark.onclick=()=>{engine.toggleStar();engine.renderQuestion();};engine.el.main.prepend(mark);
 const ids={previous:'dungeonToolPrev',next:'dungeonToolNext',labs:'dungeonLabBtn',calculator:'dungeonCalcBtn',settings:'dungeonToolbarOptions',notes:'dungeonNoteBtn',notebook:'dungeonNoteBtn',suspend:'dungeonSuspendBtn',end:'dungeonEndBlockBtn',report:'dungeonEndBlockBtn',library:'dungeonMedicalLibraryBtn'};
 for(const bar of [header,footer])bar.querySelectorAll('[data-nbme]').forEach(b=>{const action=b.dataset.nbme;b.onclick=()=>{if(action==='settings')return window.QnexNbmeLayout.settings(engine,b);if(action==='answer')return engine.toggleReveal();if(action==='submit')return engine.handleSubmit();if(action==='pause')return engine.pauseAmbossSession();if(action==='fullscreen'){const doc=document,host=doc.documentElement;const active=doc.fullscreenElement||doc.webkitFullscreenElement;const fn=active?(doc.exitFullscreen||doc.webkitExitFullscreen):(host.requestFullscreen||host.webkitRequestFullscreen);if(fn)Promise.resolve(fn.call(active?doc:host)).catch(()=>engine.showNotification('Fullscreen is unavailable in this browser.','info'));else engine.showNotification('Fullscreen is unavailable in this browser.','info');return;}root.querySelector('#'+ids[action])?.click();};if(action==='previous')b.disabled=engine.state.currentIndex===0;if(action==='next')b.disabled=engine.state.currentIndex===engine.state.questions.length-1;});
 },settings(engine,opener){
 document.getElementById('nbmeSettings')?.remove();const dialog=document.createElement('dialog');dialog.id='nbmeSettings';dialog.className='nbme-settings-panel';
 dialog.innerHTML='<header><h2>Exam settings</h2><button type="button" aria-label="Close settings">×</button></header><label>Text size<select data-setting="size"><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option></select></label><label>Theme<select data-setting="theme"><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Text alignment<select data-setting="align"><option value="left">Left</option><option value="center">Center</option><option value="justify">Justified</option></select></label><label>Split question and explanation<input type="checkbox" data-setting="split"></label><label>Theme layout<select data-setting="layout"><option value="uw">UW</option><option value="amboss">AMBOSS</option><option value="bau">BAU</option><option value="nbme">NBME Primary</option><option value="nbme-secondary">NBME Secondary</option></select></label>';
 const root=engine.el.container,size=dialog.querySelector('[data-setting=size]'),theme=dialog.querySelector('[data-setting=theme]'),align=dialog.querySelector('[data-setting=align]'),split=dialog.querySelector('[data-setting=split]');
 const layout=dialog.querySelector('[data-setting=layout]');layout.value=engine.questionLayout(engine.state.questions[engine.state.currentIndex]);layout.onchange=()=>{localStorage.setItem('qnex-dungeon-layout',layout.value);window.QnexResponsive?.closeDrawer();root.classList.remove('nbme-sidebar-open');engine.stopTimer();engine.render();dialog.close();};
 size.value=localStorage.getItem('dungeonFontSize')||'medium';theme.value=root.dataset.nbmeAppearance||'light';align.value=root.dataset.nbmeTextAlign||'left';split.checked=!!engine.state.splitView;
 size.onchange=()=>{engine.setFontSize(size.value);root.style.setProperty('--nbme-text-size',({small:16,medium:18,large:21}[size.value])+'px');};
 theme.onchange=()=>{root.dataset.nbmeAppearance=theme.value;localStorage.setItem('nbmeAppearance',theme.value);};
 align.onchange=()=>{root.dataset.nbmeTextAlign=align.value;localStorage.setItem('nbmeTextAlign',align.value);};split.onchange=()=>engine.toggleSplitView();
 const close=()=>{dialog.classList.add('closing');setTimeout(()=>dialog.close(),180);};dialog.querySelector('header button').onclick=close;dialog.onclick=event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)close();}};dialog.oncancel=event=>{event.preventDefault();close();};dialog.onclose=()=>{dialog.remove();if(opener.isConnected)opener.focus();};document.body.append(dialog);dialog.showModal();
 }};
})();
